from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os

from yacs.config import CfgNode as CN

_C = CN()

_C.OUTPUT_DIR = ''
_C.LOG_DIR = ''
_C.DATA_DIR = ''
_C.GPUS = ''
_C.WORKERS = 4
_C.PRINT_FREQ = 20
_C.AUTO_RESUME = False
_C.PIN_MEMORY = True
_C.RANK = 0

_C.CUDNN = CN()
_C.CUDNN.BENCHMARK = True
_C.CUDNN.DETERMINISTIC = False
_C.CUDNN.ENABLED = True

_C.MODEL = CN()
_C.MODEL.NAME = 'llrformer'
_C.MODEL.INIT_WEIGHTS = True
_C.MODEL.PRETRAINED = ''
_C.MODEL.NUM_JOINTS = 17
_C.MODEL.TAG_PER_JOINT = True
_C.MODEL.TARGET_TYPE = 'gaussian'
_C.MODEL.IMAGE_SIZE = [256, 256]
_C.MODEL.HEATMAP_SIZE = [64, 64]
_C.MODEL.PATCH_SIZE = [9, 3]
_C.MODEL.SIGMA = 2
_C.MODEL.HIDDEN_HEATMAP_DIM = -1
_C.MODEL.TRANSFORMER_DEPTH = 0
_C.MODEL.TRANSFORMER_HEADS = 2
_C.MODEL.TRANSFORMER_MLP_RATIO = 2
_C.MODEL.POS_EMBEDDING_TYPE = 'learnable' 
_C.MODEL.DIM = 2

_C.MODEL.DROPOUT_RATE = 0.0
_C.MODEL.ATTENTION_DROPOUT = 0.0
_C.MODEL.LAYER_NORM_EPS = 1e-5
_C.MODEL.MULTI_TRANSFORMER_DEPTH = [12, 12]
_C.MODEL.MULTI_TRANSFORMER_HEADS = [16, 16]
_C.MODEL.MULTI_DIM = [48, 48]
_C.MODEL.INIT = False
_C.MODEL.NUM_BRANCHES = 1
_C.MODEL.BASE_CHANNEL = 32

_C.MODEL.LAYERED_ATTENTION = False
_C.MODEL.ATTENTION_STRATEGY = 'standard'
_C.MODEL.HEAD_SPECIALIZATION = False
_C.MODEL.HEAD_TYPES = CN()
_C.MODEL.HEAD_TYPES.SPATIAL_HEADS = [0, 1, 2, 3]
_C.MODEL.HEAD_TYPES.TEXTURE_HEADS = [4, 5, 6, 7]
_C.MODEL.HEAD_TYPES.ANATOMICAL_HEADS = [8, 9, 10, 11]
_C.MODEL.HEAD_TYPES.GLOBAL_HEADS = [12, 13, 14, 15]

_C.MODEL.ATTENTION_CONSTRAINTS = CN()
_C.MODEL.ATTENTION_CONSTRAINTS.LOCAL_RADIUS = 32
_C.MODEL.ATTENTION_CONSTRAINTS.MEDIUM_RADIUS = 64
_C.MODEL.ATTENTION_CONSTRAINTS.GLOBAL_RADIUS = 128
_C.MODEL.ATTENTION_CONSTRAINTS.SPATIAL_WEIGHT = 0.3

_C.MODEL.USE_CROSS_SELF_ATTENTION = False
_C.MODEL.CROSS_SELF_ATTENTION_LAYERS = 6
_C.MODEL.CROSS_SELF_ATTENTION_HEADS = 8
_C.MODEL.CROSS_SELF_ATTENTION_DIM = 192
_C.MODEL.CROSS_SELF_ATTENTION_MLP_RATIO = 4
_C.MODEL.USE_POSITIONAL_ENCODING = True
_C.MODEL.POSITIONAL_ENCODING_TYPE = 'learnable'

_C.MODEL.USE_FLASH_ATTENTION = False
_C.MODEL.USE_GRADIENT_CHECKPOINTING = False
_C.MODEL.USE_MIXED_PRECISION = False

_C.MODEL.DEBUG = CN()
_C.MODEL.DEBUG.SAVE_ATTENTION_WEIGHTS = False
_C.MODEL.DEBUG.ATTENTION_LAYER_INDEX = 0

_C.MODEL.EXTRA = CN(new_allowed=True)

_C.LOSS = CN()
_C.LOSS.USE_OHKM = False
_C.LOSS.TOPK = 8
_C.LOSS.USE_TARGET_WEIGHT = True
_C.LOSS.USE_DIFFERENT_JOINTS_WEIGHT = False
_C.LOSS.TYPE = 'mse'
_C.LOSS.FOCAL_LOSS = False
_C.LOSS.FOCAL_ALPHA = 0.25
_C.LOSS.FOCAL_GAMMA = 2.0
_C.LOSS.LABEL_SMOOTHING = False
_C.LOSS.SMOOTHING_ALPHA = 0.1

_C.DATASET = CN()
_C.DATASET.ROOT = ''
_C.DATASET.DATASET = 'MyKeypointDataset'
_C.DATASET.TRAIN_SET = 'train'
_C.DATASET.TEST_SET = 'valid'
_C.DATASET.DATA_FORMAT = 'jpg'
_C.DATASET.HYBRID_JOINTS_TYPE = ''
_C.DATASET.SELECT_DATA = False

_C.DATASET.FLIP = True
_C.DATASET.SCALE_FACTOR = 0.25
_C.DATASET.ROT_FACTOR = 30.0
_C.DATASET.PROB_HALF_BODY = 0.0
_C.DATASET.NUM_JOINTS_HALF_BODY = 8
_C.DATASET.COLOR_RGB = False

_C.DATASET.MEDICAL_AUGMENTATION = False
_C.DATASET.MIXUP_CUTMIX = False
_C.DATASET.TEST_TIME_AUGMENTATION = False

_C.TRAIN = CN()

_C.TRAIN.LR_FACTOR = 0.1
_C.TRAIN.LR_STEP = [90, 110]
_C.TRAIN.LR = 0.001

_C.TRAIN.LAYERED_TRAINING = False
_C.TRAIN.FREEZE_LAYERS = []
_C.TRAIN.ATTENTION_REGULARIZATION = False
_C.TRAIN.ATTENTION_LOSS_WEIGHT = 0.1
_C.TRAIN.UNFREEZE_SCHEDULE = CN()
_C.TRAIN.UNFREEZE_SCHEDULE.EPOCH_50 = [3, 4, 5]
_C.TRAIN.UNFREEZE_SCHEDULE.EPOCH_100 = [6, 7, 8]
_C.TRAIN.UNFREEZE_SCHEDULE.EPOCH_150 = [9, 10, 11]
_C.TRAIN.UNFREEZE_SCHEDULE.EPOCH_200 = 'all'
_C.TRAIN.UNFREEZE_SCHEDULE.EPOCH_75 = [3, 4, 5]
_C.TRAIN.UNFREEZE_SCHEDULE.EPOCH_150 = [6, 7, 8]
_C.TRAIN.UNFREEZE_SCHEDULE.EPOCH_225 = [9, 10, 11]
_C.TRAIN.LR_SCHEDULER = 'MultiStepLR'
_C.TRAIN.LR_END = 0.00001
_C.TRAIN.PATIENCE = 10
_C.TRAIN.MIN_LR = 1e-7
_C.TRAIN.JOINT_WEIGHTS = False
_C.TRAIN.FEMUR_TIBIA_WEIGHT = 2.0
_C.TRAIN.KEYPOINT_WEIGHTS = []

_C.TRAIN.HIP_WEIGHT = 1.5
_C.TRAIN.FEMUR_WEIGHT = 2.5
_C.TRAIN.KNEE_WEIGHT = 1.0
_C.TRAIN.TIBIA_WEIGHT = 2.0
_C.TRAIN.ANKLE_WEIGHT = 1.3

_C.TRAIN.GRADIENT_CLIP_NORM = 1.0
_C.TRAIN.COSINE_ANNEALING = False

_C.TRAIN.OPTIMIZER = 'adam'
_C.TRAIN.MOMENTUM = 0.9
_C.TRAIN.WD = 0.0001
_C.TRAIN.NESTEROV = False
_C.TRAIN.GAMMA1 = 0.99
_C.TRAIN.GAMMA2 = 0.0

_C.TRAIN.BEGIN_EPOCH = 0
_C.TRAIN.END_EPOCH = 140

_C.TRAIN.RESUME = False
_C.TRAIN.CHECKPOINT = ''

_C.TRAIN.BATCH_SIZE_PER_GPU = 32
_C.TRAIN.SHUFFLE = True

_C.TRAIN.WARMUP_EPOCHS = 0
_C.TRAIN.WARMUP_LR = 0.000001
_C.TRAIN.GRADIENT_CLIP = 0.0
_C.TRAIN.LABEL_SMOOTHING = 0.0
_C.TRAIN.FOCAL_LOSS_ALPHA = 1.0
_C.TRAIN.FOCAL_LOSS_GAMMA = 2.0
_C.TRAIN.MIXUP_ALPHA = 0.2
_C.TRAIN.CUTMIX_ALPHA = 1.0
_C.TRAIN.CUTMIX_PROB = 0.3
_C.TRAIN.DROPOUT = 0.0
_C.TRAIN.L1_REGULARIZATION = 0.0
_C.TRAIN.L2_REGULARIZATION = 0.0

_C.TEST = CN()

_C.TEST.BATCH_SIZE_PER_GPU = 32
_C.TEST.FLIP_TEST = False
_C.TEST.POST_PROCESS = False
_C.TEST.SHIFT_HEATMAP = False
_C.TEST.BLUR_KERNEL = 11
_C.TEST.USE_GPU = True

_C.TEST.TEST_TIME_AUGMENTATION = False
_C.TEST.TTA_NUM_AUGMENTS = 5

_C.TEST.USE_GT_BBOX = False

_C.DEBUG = CN()
_C.DEBUG.SAVE_BATCH_IMAGES_GT = False
_C.DEBUG.SAVE_BATCH_IMAGES_PRED = False
_C.DEBUG.SAVE_HEATMAPS_GT = False
_C.DEBUG.SAVE_HEATMAPS_PRED = False
_C.DEBUG.SAVE_ATTENTION_WEIGHTS = False
_C.DEBUG.ATTENTION_LAYER_INDEX = 0
_C.DEBUG.DEBUG = False

_C.TEST.IMAGE_THRE = 0.1
_C.TEST.NMS_THRE = 0.6
_C.TEST.SOFT_NMS = False
_C.TEST.OKS_THRE = 0.5
_C.TEST.IN_VIS_THRE = 0.0
_C.TEST.COCO_BBOX_FILE = ''
_C.TEST.BBOX_THRE = 1.0
_C.TEST.MODEL_FILE = ''

_C.EVALUATION = CN()
_C.EVALUATION.METRICS = ['PCK', 'AUC', 'NME', 'MED']
_C.EVALUATION.PCK_THRESHOLDS = [0.005, 0.01, 0.02, 0.05]
_C.EVALUATION.AUC = True
_C.EVALUATION.MED = True
_C.EVALUATION.NME = True
_C.EVALUATION.CCC = True
_C.EVALUATION.REGIONS = CN()
_C.EVALUATION.REGIONS.HIP = []
_C.EVALUATION.REGIONS.FEMUR = []
_C.EVALUATION.REGIONS.KNEE = []
_C.EVALUATION.REGIONS.TIBIA = []
_C.EVALUATION.REGIONS.ANKLE = []

_C.CHECKPOINT = CN()
_C.CHECKPOINT.SAVE_FREQ = 10
_C.CHECKPOINT.PATIENCE = 20
_C.CHECKPOINT.SAVE_BEST = True
_C.CHECKPOINT.SAVE_LAST = True
_C.CHECKPOINT.RESUME = False
_C.CHECKPOINT.CHECKPOINT = ''

_C.MEDICAL_AUGMENTATION = CN()
_C.MEDICAL_AUGMENTATION.BRIGHTNESS_CONTRAST = [0.8, 1.2, 0.8, 1.2]
_C.MEDICAL_AUGMENTATION.NOISE_INTENSITY = 0.05
_C.MEDICAL_AUGMENTATION.BLUR_INTENSITY = 0.3
_C.MEDICAL_AUGMENTATION.SHARPNESS = 0.2
_C.MEDICAL_AUGMENTATION.CLAHE = True
_C.MEDICAL_AUGMENTATION.ELASTIC_TRANSFORM = True
_C.MEDICAL_AUGMENTATION.GRID_DISTORTION = True
_C.EVALUATION.REGIONS = CN(new_allowed=True)

def update_config(cfg, args):
    """Update configuration from YAML file and command line arguments."""
    if isinstance(args, str):
        cfg.merge_from_file(args)
        return
    else:
        cfg.merge_from_file(args.cfg)

    if hasattr(args, 'modelDir') and args.modelDir:
        cfg.OUTPUT_DIR = args.modelDir

    if hasattr(args, 'logDir') and args.logDir:
        cfg.LOG_DIR = args.logDir

    if hasattr(args, 'dataDir') and args.dataDir:
        cfg.DATA_DIR = args.dataDir

    cfg.defrost()
    
    cfg.DATASET.ROOT = os.path.join(
        cfg.DATA_DIR, cfg.DATASET.ROOT
    )

    if cfg.MODEL.PRETRAINED:
        cfg.MODEL.PRETRAINED = os.path.join(
            cfg.DATA_DIR, cfg.MODEL.PRETRAINED
        )

    if cfg.TEST.MODEL_FILE:
        if not os.path.isabs(cfg.TEST.MODEL_FILE):
            cfg.TEST.MODEL_FILE = os.path.join(
                cfg.DATA_DIR, cfg.TEST.MODEL_FILE
            )

    if isinstance(cfg.GPUS, str):
        gpus = [int(x) for x in cfg.GPUS.split(',') if x.strip()]
    else:
        gpus = list(cfg.GPUS)
    cfg.GPUS = gpus

    cfg.freeze()


if __name__ == '__main__':
    import sys
    with open(sys.argv[1], 'w') as f:
        print(_C, file=f)

